### ISSUE TITLE
Add next spell rank warning/expected to notification

### ISSUE THREAD

**Issue by chorp-cpu** [valkyrnstudios/RankSentinel#19]
Instead of you cast spell id 99999 and need to train a more helpful message would be 
you cast frostbolt rank 4 while the max for your level is rank 13, perhaps you need to train or fix your hotbutton

**Comment by Gogo1951** [comment]
Good to link the spell name, totally agree.

There are times when you can't always link to the max level. Like... the books in AQ20. Probably not great to tell people to upgrade the moment those drop. Good to give everyone a patch or two to catch up.

Good to also include some amount of branding to help people know what add-on is making the announcement.

Would suggest something like this:

{rt7}  RankSentinel : Friendly Reminder! You just used a low rank of [LINK TO SPELL]. Please check your Action Bars or visit your Class Trainer to make sure you've got the right ability for your level.

**Comment by SabreValkyrn** [comment]
The current notification should be

> {rt7} RankSentinel detectedyou  just used a low rank of [Spell Tooltip]. You might be missing training or using an outdated ability shortcut.

**Comment by chorp-cpu** [comment]
I was thinking:

{rt7} RankSentinel detected you just used a low rank of [Spell Tooltip]. You might be missing training or using an outdated ability shortcut for rank XX

where xx is the highest rank listed from abilitydata.

**Comment by SabreValkyrn** [comment]
As of v1.1.0

>{rt7} RankSentinel detected you just used a low rank of [Spell Tooltip], next rank available at N. You might be missing training or using an outdated ability shortcut.
