### ISSUE TITLE
Support SoM/ClassicEra

### ISSUE THREAD

**Issue by SabreValkyrn** [valkyrnstudios/RankSentinel#20]
- [x] Build ability GSheet
- [x] Update Build.py for BCC+SoM/ClassicEra
- [x] Support multi-toc
- [x] Only load expansion-specific ability data

**Comment by SabreValkyrn** [comment]
Foundation added in #22

**Comment by Gogo1951** [comment]
Nice, I'll get the reviewed data over to you soon!

**Comment by SabreValkyrn** [comment]
#26 should have finished support for SoM.

Will be released with v1.2.0

**Comment by SabreValkyrn** [comment]
So 1.13.0/1 had spellID in combat log, then 1.13.2 removed it. https://wowpedia.fandom.com/wiki/Patch_1.13.2/API_changes

> The Combat Log no longer has access to Spell IDs, they are always returned as 0, since they were only added to the combat log in patch 2.4
> `UNIT_SPELLCAST_*` events only fire for the player.

https://wowpedia.fandom.com/wiki/COMBAT_LOG_EVENT

> Spell IDs are always 0 on classic_era.

Trimmed functionality for SoM, using https://wowpedia.fandom.com/wiki/UNIT_SPELLCAST_SUCCEEDED #27
