### ISSUE TITLE
Improve player ignore

### ISSUE THREAD

**Issue by mfsoup** [valkyrnstudios/RankSentinel#28]
`/sentinel ignore` and `/ranksentinel ignore` work on players inside my group but not players outside my group. I get the following error: 

```
Message: Interface\AddOns\RankSentinel\Cache.lua:5: table index is nil
Time: Tue Dec 28 01:28:57 2021
Count: 8
Stack: Interface\AddOns\RankSentinel\Cache.lua:5: table index is nil
[string "@Interface\SharedXML\SharedBasicControls.lua"]:297: in function <Interface\SharedXML\SharedBasicControls.lua:296>
[string "=[C]"]: ?
[string "@Interface\AddOns\RankSentinel\Cache.lua"]:5: in function `IgnorePlayer'
[string "@Interface\AddOns\RankSentinel\RankSentinel.lua"]:145: in function `ChatCommand'
[string "@Interface\AddOns\RankSentinel\RankSentinel.lua"]:52: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:4825: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4488: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4524: in function <Interface\FrameXML\ChatFrame.lua:4520>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: errorMessage = "Interface\AddOns\RankSentinel\Cache.lua:5: table index is nil"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:279
MESSAGE_TYPE_ERROR = 0
```

Also, using `/sentinel ignore` on an already ignored player doesn't remove the ignore (or at least the message doesn't say it does).

Apologies for making this 3 issues in one but a command like `/sentinel ignore` or `/sentinel ignores` to list ignored players would be useful

Version 1.2.2-bcc

**Comment by SabreValkyrn** [comment]
I'm curious, what's the use case for ignoring players outside your group? Notifications shouldn't be sent if a player isn't in your party/raid.

**Comment by SabreValkyrn** [comment]
- [ ] List currently ignored players
- [ ] Support removing player from ignore list
- [ ] Handle parse/typo/invalid input better, unit may need to be in the same zone to be ignored

**Comment by mfsoup** [comment]
> I'm curious, what's the use case for ignoring players outside your group? Notifications shouldn't be sent if a player isn't in your party/raid.

I happened to remember some guildies who use a couple of uncommon deranks while outside raid.

**Comment by SabreValkyrn** [comment]
Couldn't do everything given functional limitations, but unignore and listing ignore is (partially) supported.

The problem boils down to ignores being on the playerGUID, so not human readable.

Changes in v1.3.1
