### ISSUE TITLE
Overhaul notifications messages

### ISSUE THREAD

**Issue by SabreValkyrn** [valkyrnstudios/RankSentinel#32]
- [x] Convert to friendlier phrasing
- [x] Simplify cluster broadcasted notification
- [x] Avoid message duplication on subsequent alerts
- [x] Simplify queued notification
- [x] Add rank to notifications

For both in-combat and queued notifications, all happen at once with the same text.

For queued messages, subsequent notifications should be truncated

>The next rank of [spell link] is also available at xx.

**Comment by SabreValkyrn** [comment]
Also related, sending too many whispers during queue processing could result in a mute.

If too many messages, just wait for the next combat?

**Comment by Gogo1951** [comment]
Loving this add-on, and it's really finding a lot of stuff. Every run I go into... it goes off. (=

That said, some people are really sensitive to being told there are improvement options available.

Would suggest softening language away from the "mistake detected" tone, and switch it up to:

> {rt7} RankSentinel : Friendly reminder to be the best you that you can be! There's a higher rank of [XYZ] available after level X. Please check your action bars or visit your trainer when you can. Cheers!

... and for pets

> {rt7} RankSentinel : Friendly reminder to help [Fido] be a better pet! There's a higher rank of [XYZ] available after level X. Cheers!

**Comment by SabreValkyrn** [comment]
I think you'll be excited about the newest alpha, major changes so don't want to release it just yet.
