### ISSUE TITLE
Scourge Strike Doesn't Have Rank 7

### ISSUE THREAD

**Issue by Gogo1951** [valkyrnstudios/RankSentinel#59]
![image](https://user-images.githubusercontent.com/55365231/183324105-9dd3e51d-8594-4836-a5f3-afd70c972ce8.png)

![image](https://user-images.githubusercontent.com/55365231/183324136-c7582bd7-1ef9-4642-9b51-aa082d1d2674.png)

Only went to 6 in the data, but the add-on thinks there's a Rank 7.

https://www.wowhead.com/wotlk/spell=49921/plague-strike

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/183324506-53c85086-e4e9-43f3-bc11-9b8cedcd94b2.png)

**Comment by Gogo1951** [comment]
Some how this got included in the Plague Strike group. 
![image](https://user-images.githubusercontent.com/55365231/183324632-40930cc5-df77-4a5e-9f27-df1b45eb7b93.png)

**Comment by Gogo1951** [comment]
This group of Glyphed Death Coil seems to have gotten left out, but one of the spells incorrectly got added to the Plague Strike group. May be worth checking the groupings, but that's the only one I found that was odd for DKs.

**Comment by SabreValkyrn** [comment]
That is not the right GSheet, per README. https://docs.google.com/spreadsheets/d/1jtx1WyfChzACzh0WBWANtrqkRtS3D-zPWqs3eOnyVvY/edit

![image](https://user-images.githubusercontent.com/61754281/183326187-3582be04-391b-4934-ae83-7f4247db229d.png)

But that did indeed get lumped into `{ 45462, 49917, 49918, 49919, 49920, 49921, 62904 },` Plague Strike which is confusing.

**Comment by SabreValkyrn** [comment]
Probably fixed by this change.

![image](https://user-images.githubusercontent.com/61754281/183329160-e2c0aaeb-1d38-4730-bc62-2e81ef6cb0e0.png)

v2.0.5c
