### ISSUE TITLE
Option: only whisper lv 80 chars

### ISSUE THREAD

**Issue by Leylaa2** [valkyrnstudios/RankSentinel#67]
Hey,
is there a option to only whisper lv 80 chars?
spamming all the ppl leveling is not pleasant :)

Greetings :)

**Comment by Cellis9421** [comment]
Yes, this is a great idea. The idea of this add-on is great, its implementation is toxic—any toggles to accommodate more customization would be amazing.

**Comment by SabreValkyrn** [comment]
> its implementation is toxic

A whisper directly to the person is toxic? There's literally no way people won't get bent being told they doing something wrong.

Regardless, this is on my roadmap for 2.3.0, just been too busy to do all the things I wanted to. Overhaling settings so stuff like this is easier to add in the future, but a fair bit of work to get there.

**Comment by SabreValkyrn** [comment]
Implemented in v2.3.0, whenever I get that out.
