### ISSUE TITLE
Explosive Shot Rank 3

### ISSUE THREAD

**Issue by ethanf22** [valkyrnstudios/RankSentinel#71]
I've got a hunter that uses Explosive Shot (Rank 3) in his rotation. There's an explanation on Reddit of why it's used by u/JC3EXD: https://www.reddit.com/r/classicwow/comments/ypaxh0/our_tank_at_malygos/

> For context, I play SV hunter, and its not widely known (unless keeping up on hunter discord posts) that during Lock&Load procs, you can actually use different ranks of Explosive Shot to STACK the DoT effect of ability, rather than override it with the same rank. Lock&Load is a proc that occurs from damage/pulse ticks of traps or black arrow that gives you 2 additional charges of Explosive Shot or Arcane Shot with no cooldown (except the gcd). Explosive Shot is the bread & butter ability for SV hunters, so this is great. Explosive Shot, upon reaching the target, instantly deals a tick of fire damage and applies a short DoT, doing 2 more ticks of fire damage one second apart. For reference, as a 214 ilvl hunter in a 25man setting, each tick can crit for over 7k (making this a potential 21k+ damage ability from a single GCD).

> The issue is, if you decide to simply press Explosive Shot 3 times in a row (on the GCD) your initial DoT effect is actually replaced by the new one. If you didn't get all three ticks off before applying a new one, the remaining ones are lost. This is known as Explosive Clipping. Usually, you either have to manually time it so that you press your Explosive Shot just as the final tick is about to go off (allowing for travel time on the shot) or you have a WA that basically tells you based on your distance from the boss when you need to press it again to not clip. Because its such a precisely timed ability and you need to get all 3 Explosive Shots off during the L&L window, you usually dont press any buttons whilst waiting for the right time to press ES again (its only just longer than the gcd wait so you dont wait long, but hard-casting something else puts you at risk of not getting all 3 Explosive Shots out before L&L expires). You can use instant abilities, but basically can't cast steady shot during this time. It creates a stutter in what is otherwise a fluid rotation.

> However... during Lock&Load, you can actually alternate ranks of Explosive Shot and it won't consume the existing DoT effect, but actually stack them. So, you get the L&L proc, press Explosive Shot max rank (4), then use your next gcd on Explosive Shot (rank 3), then your third on ES (r4, as by this time your initial rank 4 cast should have done all 3 damage ticks or will have done by the time your final shot lands). Then you go back to your rotation with zero downtime or stuttering/pausing for procs. Sure, there is a loss of damage in the lowered rank ability, but its outweighed by the gain achieved from not pausing your rotation during that window (and the damage difference between rank 3 and 4 isn't huge).

**Comment by SabreValkyrn** [comment]
https://github.com/valkyrnstudios/RankSentinel/commit/fb1b9fd61e83dc9cbcc270c065b978bf0ac1ea0f

Updated in 2.2.3
