### ISSUE TITLE
Version Check & Disable for Outdated RankSentinel 

### ISSUE THREAD

**Issue by Gogo1951** [valkyrnstudios/RankSentinel#72]
Far too often, out-dated RankSentinel makes bugs persist longer than they need to.

Suggest adding a version check, showing that RankSentinel is out of date, and disabling it until the user updates.

Feel free to use any of the code from Groupie for version check. 

To remind users to update... you can post a message to the user in place of messages it would send casters of low-rank abilities, "RankSentinel detected {Named} used a low-rank of {Spell}, please update your add-ons to have RankSentinel continue to send messages."

Look, everyone hates all the UX I come up with, but I think this would be better than spamming out low-rank stuff when we fix bugs.

Maybe the ship has sailed already, but better late than never.

**Comment by Gogo1951** [comment]
RankWatch : We detected you have an out-dated RankWatch!

Kind of ironic, and funny. (=

**Comment by SabreValkyrn** [comment]
#77 merged this functionality in, just hard to fully test solo. Works with other clients sending data to my dev version.
