### ISSUE TITLE
Request for Creator / Sponsor Names in Tooltips

### ISSUE THREAD

**Issue by Gogo1951** [valkyrnstudios/RankSentinel#79]
Nudge people to contribute a bit.

![image](https://user-images.githubusercontent.com/55365231/209600148-53981e2f-d3f9-4ec8-ab71-66af02372b44.png)

Also, request to have anyone on this list automatically made leader in groups.

Take whatever code you want from Groupie / GogoLoot / GDKPd. This is a very light-weight check on GUIDs.

**Comment by Gogo1951** [comment]
Do you want an icon?

**Comment by Gogo1951** [comment]
https://github.com/Gogo1951/Groupie/blob/main/Core.lua#L1993 -- tooltips

https://github.com/Gogo1951/Groupie/blob/28d2259b7f759a9b0e2f17584a4a02533ff24573/Globals.lua#L841 -- player data

**Comment by SabreValkyrn** [comment]
I don't find value in adding this for 2 people.

> request to have anyone on this list automatically made leader in groups.

Is something I'm partially working on, but clustering foundation isn't setup for that at all so it's a fair bit of work.
