### ISSUE TITLE
Temporarily ignore players who just levelled

### ISSUE THREAD

**Issue by SabreValkyrn** [valkyrnstudios/RankSentinel#80]
Add player dings to session cache and ignore further alerts. Small chance to hide actual alerts, but far less irritating to ding and get immediately hit with a bunch of alerts.

**Comment by Gogo1951** [comment]
That's why they get a 1-level grace period. =P

**Comment by SabreValkyrn** [comment]
Not sure I follow that comment. Given someone can't be level 81 in Wrath, dinging level 80 inside a dungeon results in immediate spam.

Another scenario, if a level 76 gets alerted for level 74 spells, then dings 77 in a dungeon, they get alerted for those same level 74 spells.

**Comment by Gogo1951** [comment]
Hmm... the not hitting someone twice for the same infraction though. That may be valid. Like if we already reminded them about Heroic Strike, and they level, and we remind them about Heroic Strike again... yeah that's annoying. 

How about just only remind for one ability group (Heroic Strike) per session per toon, regardless of level change? I think that works. Just add a check, "Have I already hit him about Heroic Strike this instance?"

**Comment by SabreValkyrn** [comment]
One AbilityGroup notification per session is elegant, I was going to look for a previous spell index from an earlier level.
