### ISSUE TITLE
Request for "Leader" to be "Sticky"

### ISSUE THREAD

**Issue by Gogo1951** [valkyrnstudios/RankSentinel#81]
If you are the "leader," and you wipe, or change zones, or add someone to a raid, odds are you will no longer be the leader.

Maybe add a Join Group time stamp, and go off of whoever is first? Or maybe have a flag where if you set yourself leader it stays put? \ 

Trivial, but with more people adopting the add-on it's way more common to see a few people running it.

This came up in a raid, I showed a guild officer how to set themselves as leader, but then they complained that it didn't stick over the night. They had to keep re-setting themselves as leader.

**Comment by SabreValkyrn** [comment]
This is already 80%+ done on `main`/alpha.

**Comment by SabreValkyrn** [comment]
Should be adequately handled in next release, once a leader in a raid is set they shouldn't get changed unless someone is using an old version or leader leaves the group.
