### ISSUE TITLE
Low rank Penance not being detected

### ISSUE THREAD

**Issue by trey-k** [valkyrnstudios/RankSentinel#82]
Didn't have any notifications/whispers during raid to our priest but logs show a rank 1 Penance being used, tested with the priest in party and no detection occurred shuffling through every rank. Spell ID for rank 1 in logs is listed as [47750](https://www.wowhead.com/wotlk/spell=47750/penance)

**Comment by SabreValkyrn** [comment]
HM. Talented abilities have been a pain.

Penance Rank 1 in current data is [47540](https://www.wowhead.com/wotlk/spell=47540/penance)


Priest | Penance | 60 | 1 | 47540
-- | -- | -- | -- | --
Priest | Penance | 70 | 2 | 53005
Priest | Penance | 75 | 3 | 53006
Priest | Penance | 80 | 4 | 53007

**Comment by Gogo1951** [comment]
I don't see Penance as being 47750.

https://wotlkdb.com/?spell=47540
https://www.wowhead.com/wotlk/spell=47540/penance

What I think shows is both numbers in the log. One for cast, and one for each "tick" of the heal.

As long as we track 1, it'll notify correctly. I'll test it later on my priest.

**Comment by SabreValkyrn** [comment]
Awesome, thanks. I don't have a Priest at all to check this with

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/224453266-189333e9-65dc-432c-8062-bc419f38b25b.png)
![image](https://user-images.githubusercontent.com/55365231/224453288-3e1e57a2-7679-472a-89e7-869c81c8908e.png)
![image](https://user-images.githubusercontent.com/55365231/224453305-3b4bccac-5d7e-44ae-910f-2fdb895063e2.png)
![image](https://user-images.githubusercontent.com/55365231/224453314-6beffe3c-57b7-4f3a-8500-c646b9a11ec4.png)

But... I don't get an alert when Rank 1 is cast.

**Comment by Gogo1951** [comment]
Spell in combat log seems to line up too.

![image](https://user-images.githubusercontent.com/55365231/224453427-5bf4f898-312b-4816-a3cb-f6360bcf3a28.png)

**Comment by Gogo1951** [comment]
Healing IDs

47750
52983
52984
52985

Damage

No IDs shown... odd.
