### ISSUE TITLE
Got this error, but I don't think it's really RankSentinel

### ISSUE THREAD

**Issue by Gogo1951** [valkyrnstudios/RankSentinel#83]
5x SendChatMessage(): Invalid escape code in chat message
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\RankSentinel\Cache.lua"]:43: in function `ProcessQueuedNotifications'
[string "@Interface\AddOns\RankSentinel\RankSentinel-v2.3.2.lua"]:63: in function <Interface\AddOns\RankSentinel\RankSentinel.lua:63>

Locals:
(*temporary) = "|TInterface\TargetingFrame\UI-RaidTargetingIcon_7.blp:0|t Grossechatte (Rank 0) was used14, there's a newer rank at level 0."
(*temporary) = "WHISPER"
(*temporary) = nil
(*temporary) = "Grossechatte"

**Comment by SabreValkyrn** [comment]
Did you enable whispers after notifications were queued with whispers disabled?
