### ISSUE TITLE
Life Tap downranking triggers warnings

### ISSUE THREAD

**Issue by Anonomit** [valkyrnstudios/RankSentinel#84]
There's always a valid reason to downrank Life Tap. It's commonly downranked one or two ranks to consume less health and/or avoid overflowing on mana. Currently, only rank 1 is ignored. This is a common rank to use since it's able to proc certain spell effects, but other ranks are needed when the goal is to restore mana without wasting health. I think the best solution is to ignore all ranks of Life Tap.

**Comment by Gogo1951** [comment]
For TBC... here's what a buddy had to say about Life Tap.

FYI @SabreValkyrn (why I left Life Tap) on the list for TBC... in case anyone asks. (=

> For a raiding Warlock, Max Rank Life Tap is superior in almost every scenario.
> 
> The primary goal of a Warlock in a raid environment is to convert Health into Mana as efficiently as possible to minimize the time spent not casting damage spells. Using a lower rank of Life Tap works against this goal for two main reasons:
>  
> **First - The Global Cooldown (GCD) is Your Most Valuable Resource**
> 
> Every time you press Life Tap, you spend 1.5 seconds (the Global Cooldown) doing zero damage.
> 
> Max Rank: Returns a massive chunk of mana, often fueling 3–4 Shadow Bolts per tap.
> 
> Downranked: Returns significantly less mana, forcing you to tap twice (wasting 3 seconds) to get the same mana you could have gained in 1.5 seconds.
> 
> Raiding is a race to fit as many Shadow Bolts/Incinerates as possible into the fight duration. Minimizing the number of times you have to press Life Tap increases your overall DPS.
>  
> **Second - Spell Power Scaling**
> 
> In TBC, Life Tap scales generously with your Spell Power (approximately an 80% coefficient).
> 
> Rank 3+: Receives the full benefit of your Spell Power gear.
> 
> Ranks 1 & 2: Suffer from a "downranking penalty," meaning they gain significantly less benefit from your +Damage gear.
> 
> Because TBC Warlocks stack significant Spell Power, a Max Rank Life Tap gives you a massive return on investment that lower ranks cannot match.
> 
> **The Only Niche Exception... Survival**
> 
> The only time you might consider a lower rank is if you are critically low on health (e.g., 500 HP) and a Max Rank tap would literally kill you, but you need just enough mana for one final Shadowburn or Shadow Bolt to kill a boss. However, in 99.99% of cases, it is better to simply use a Healthstone, potion, or wait for a heal rather than keep a downranked spell on your bars for this rare edge case.

**Comment by Anonomit** [comment]
I can understand the reasoning, and I agree that it makes sense not to downrank life tap while standing still during a raid boss fight. It has obvious use cases outside of that. Even *during* a raid boss fight, if there is downtime such as a movement phase where you can tap up to full mana, downranking becomes the optimal choice if you don't need max rank to hit full mana. The huge majority of spam I got from people using the addon was outside of raid boss encounters.

I would personally still argue that downranking life tap could be considered in any situation where you want to tap up to full mana. This would most often be outside of combat, or at the end of a trash fight when you don't want to make the healer wait on your to finish tapping before they start to drink. It's so easy to bind a modifier key or something that lets you downrank and gain 15% mana instead of 30% and not waste health. It's constantly useful when you don't have a healer, such as when leveling (though this is not a time when you will catch a lot of spam messages for it anyway).

As I remember things, you don't want to deviate from that particular list, so I'm not really expecting anything to change for life tap at this point. Even though it seems like we'll continue to disagree on this, I appreciate the well-explained response. Maybe an alternative solution could be to avoid sending whispers to other addon users? I think it can safely be assumed that anyone else running the same addon is already aware of their downranked abilities, and is using their own judgement instead of the addon's.

I haven't played in a while, but I remember the spam was annoying enough to me that I ended up writing my own whisper blocker and auto-reply explaining the false positive and informing the person of the chat command to turn off whispers. I believe that there was no options interface for that setting and few people were even aware they could do it, though things may have changed since then.

**Comment by Gogo1951** [comment]
> I haven't played in a while, but I remember the spam was annoying enough to me that I ended up writing my own whisper blocker and auto-reply explaining the false positive and informing the person of the chat command to turn off whispers.

Yikes.

Just to clarify one small point... The add-on is for people who care about their raid team's performance, and / or people who run a lot of PUGs.

I get that there are people out there like yourself who can't stomach anyone telling them anything about the game. And you do you man. I don't have a horse in that race.

This add-on does go off quite a bit in raids, it's true. But most people are thankful for the information that their bars / macros have outdated spells on them.

<img width="938" height="584" alt="Image" src="https://github.com/user-attachments/assets/9c782e35-c1fc-40c2-9396-e62214b6928d" />

Past that, I think the spell list is defensible -- and it's been reviewed (the original list at least) by a leader on all of the official class Discords. The life tap comment above came from a Warlock lead from a guild that sets speed records.

His candid comment to me when I asked about down-ranking Life Tap was, "Just let the healers parse, man." Ha.
