### ISSUE TITLE
Season of Discovery Support + Classic Era Client 1.15.0 Support

### ISSUE THREAD

**Issue by boktai1000** [valkyrnstudios/RankSentinel#85]
Just opening up an issue/request to update for SoD Support, of which there may be multiple issues related to it. Ideally, version parity or maybe even multi-toc support with the Wrath version.

Thanks!

**Comment by SabreValkyrn** [comment]
Updated libraries, added Classic toc, and rebuilt AbilityData.

I don't have time to entirely test on SoD+Wrath right now, please give the latest Alpha release [v2.4.0-5-gd274870-classic](https://legacy.curseforge.com/wow/addons/ranksentinel/files/4947759) a try when it publishes.

**Comment by boktai1000** [comment]
So I've been playing SoD with the latest alpha you posted, but unfortunately it seems like it's not working. No Lua errors, but it's simply not reporting any out of date spells/etc for ones I know are outdated.

![image](https://github.com/valkyrnstudios/RankSentinel/assets/9054563/79658b35-f722-43a6-b625-818c85a79f1e)
![image](https://github.com/valkyrnstudios/RankSentinel/assets/9054563/6810e535-eb80-44c0-9a87-1d9005acbdad)

**Comment by SabreValkyrn** [comment]
Try enabling debug with `/sentinel debug`, I'll test on Era/HC with an existing level 10/11 toon to see what the issue is.

But one big thing with SoD, all the runes and any non-standard spell levels would be additional complications. I also haven't checked if the core spell lists are any different or not.

**Comment by boktai1000** [comment]
I added a WA as well SpellRankWatcher to double check which is what you may see here, but here's some of what I'm seeing with Heroic Strike for example:

![image](https://github.com/valkyrnstudios/RankSentinel/assets/9054563/026f4cd2-e5f0-462e-b906-0132ecd9d117)

![image](https://github.com/valkyrnstudios/RankSentinel/assets/9054563/7affdcd6-e1c5-478a-80af-b185e0170bca)

![image](https://github.com/valkyrnstudios/RankSentinel/assets/9054563/b4aa2d62-a541-42dd-94e2-0a3bb1b07794)

Rank 3 is available - https://www.wowhead.com/classic/spell=285/heroic-strike I'm at level 16 for example and this is a fresh /reload to make sure. Hope this helps!

**Comment by SabreValkyrn** [comment]
Thanks, that helps me explain what's going on.

* You're level 16
* Heroic Strike(Rank 3) is available at level 16
* "Casted 284, next rank (285) available at 16, isMax true"
  * Casted Rank 2, Rank 3 available at 16, isMax true
* Level 10-19 has a 3-4 level forgiveness window, because lower leveling is so much faster (in TBC/Wrath)
  * https://github.com/valkyrnstudios/RankSentinel/blob/d2748703b857b6c2cd0e2bfd21bc5f3323771ba4/Utilities.lua#L134-L148
  * Since level cap is 25, not sure if narrower forgiveness windows would be good or just annoying


Works for a level 13 hunter on Era

```
[16:04:07] Rank Sentinel: Broadcasting LEAD: Kaytla,999
[16:04:20] Rank Sentinel: Casted 1978, next rank (13549) available at 10, isMax false
[16:04:20] Rank Sentinel:  Serpent Sting (Rank 1) was used, there's a newer rank at level 10.
[16:04:20] Rank Sentinel: Broadcasting NOTIFY: Player-5107-017BDE78-13-1978
```

My level 10 on HC is a Rogue so can't downrank to validate and don't have a toon on SoD at all yet.

**Comment by boktai1000** [comment]
Ah! I understand - would a configurable forgiveness window make sense? It wasn't clear or apparent to me at least until you mentioned it, but if I saw a setting it might have made sense, and maybe players could adjust as they deem necessary.

Maybe that would allow the best of both worlds? Not sure, just throwing it out there! :) Thanks so much for the detailed analysis and reply!

**Comment by SabreValkyrn** [comment]
> would a configurable forgiveness window make sense? It wasn't clear or apparent to me at least until you mentioned it, but if I saw a setting it might have made sense, and maybe players could adjust as they deem necessary.

I was just thinking about that actually, the only way I'd be comfortable with it is a setting for yourself, which would be very easy to change IsHighestAlertableRank to.

I just don't want someone (whether helpfully or griefing) set the value to `0` and spam everyone with my addon name.

**Comment by boktai1000** [comment]
Absolutely! It's your addon and your name out there, so whatever makes sense and you're effectively signing yourself up for. Perhaps as feedback or my opinion on it, I'd say some sort of slider that lets us adjust the forgiveness and the default could just be what it is, and maybe a warning or something to let people know about it being spammy if it's set to same level spells/etc. 

Just thinking how could you both reduce the people like me wondering if it's working but also prevent people from spamming and what type of compromise, maybe folks like myself are far and few between compared to the spammers though.

Just my thoughts and $0.02 for ya! Thanks again for the great addon and feedback.

**Comment by SabreValkyrn** [comment]
`v2.5.0` on its way out, I'll see about that instant feedback toggle at some point relatively shortly.
