### ISSUE TITLE
Season of Discovery - exclude in ashenvale

### ISSUE THREAD

**Issue by linkx2252** [valkyrnstudios/RankSentinel#87]
Thanks for updating the addon for SoD, it is great as a raid leader for new players / people who may have forgotten to get skill ups.

Is there an easy way / able to add an option to not use this addon in Ashenvale? I want the addon for raids but don't want to spam people in Ashenvale during the PvP event.

**Comment by SabreValkyrn** [comment]
I don't SoD, but from reading <https://www.wowhead.com/classic/guide/season-of-discovery/battle-for-ashenvale-world-pvp-event> it seems like Hellfire or Tangermarsh kind of thing. Is there a buff or anything you get when participating?

Ashenvale is a very wide level range (19-30), so flat disabling all monitoring for 11 levels (or 19-25) might not be ideal. You can disable whispers as a temporary measure when you're in the zone.

On a somewhat related note, I should make sure level 25 is calculated as the max and doesn't have level forgiveness built-in.

**Comment by linkx2252** [comment]
Hey, thanks for the reply.

No buff during the event unfortunately...maybe the logic could be:

If all 4 are true, disable whisper / raid print out:

if level 25
if in Ashenvale
if pvp flag = on
if in raid

That would eliminate some false positives? And wouldn't mess with classic era etc.
