### ISSUE TITLE
Whitelist Frost Nova (Rank 1) - mage

### ISSUE THREAD

**Issue by linkx2252** [valkyrnstudios/RankSentinel#88]
Most rages run r1 frost nova forever because of the mana cost - recommend white listing this from the addon.

**Comment by SabreValkyrn** [comment]
Where? Classic? SoD? Wrath?

**Comment by linkx2252** [comment]
Sorry, this is for SoD and classic/era.

**Comment by SabreValkyrn** [comment]
Hm, frost nova r1 is indeed not excluded for Classic.

Rain of Fire r1 is though.

**Comment by Gogo1951** [comment]
If it were up to me it would spam every Mage casting Frost Nova in PVE and be like, "Hey idiot, stop making it harder for your tank to gather things up." =P

This is the single biggest annoying issue to tank through. Mages deciding where you have to stop pulling by casting Frost Nova... usually in the wrong spot so a healer gets hit. =P

Ha.

**Comment by axlroden** [comment]
exactly, rank 1 frost nova in any classic variant cost less money, so should be the only spell mages cast. 
Since classic and wrath have different spell libraries, it should be an easy fix.. 
line 1117

**Comment by Gogo1951** [comment]
Nova 1 is the only spell I've seen that likely should be whitelisted. It'd be good to make this fix.

**Comment by SabreValkyrn** [comment]
Removed in latest release, sorry I suck and took 5ever. :/
